### ISSUE TITLE
Two small icon issues

### ISSUE THREAD

**Issue by somepaulo** [epilys/rlr#8]
The `.png` icon you're using on the main page has a white background, which looks weird on GitHub in night mode.

The name of the symbolic icon should have a dash instead of a dot after `rlr` like so: `rlr-symbolic.svg`.

![Screenshot from 2022-10-07 16-46-55](https://user-images.githubusercontent.com/15643750/194595495-01ed5491-073c-442f-8168-a01f72d7876a.png)

**Comment by epilys** [comment]
Thanks! :)
